foreground            #e6e1cf
background            #0f1419
selection_foreground  #0f1419
selection_background  #e6e1cf
cursor                #e6e1cf

color0  #161b22
color8  #5c6773
color1  #ff7733
color9  #ff7733
color2  #b8cc52
color10 #b8cc52
color3  #ffb454
color11 #ffb454
color4  #59c2ff
color12 #59c2ff
color5  #f07178
color13 #f07178
color6  #39adb5
color14 #39adb5
color7  #e6e1cf
color15 #ffffff

font_family      family="CommitMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0

repaint_delay    8
input_delay      3
sync_to_monitor  yes

remember_window_size  no
initial_window_width  1000
initial_window_height 650
window_padding_width  4
confirm_os_window_close 0

tab_bar_style        powerline
active_tab_font_style bold

detect_urls yes
copy_on_select yes
enable_audio_bell no
