foreground  #e6e1cf
background  #0f1419
cursorColor #ffb454
color0      #161b22
color8      #5c6773
color1      #ff7733
color9      #ff7733
color2      #b8cc52
color10     #b8cc52
color3      #ffb454
color11     #ffb454
color4      #59c2ff
color12     #59c2ff
color5      #f07178
color13     #f07178
color6      #39adb5
color14     #39adb5
color7      #e6e1cf
color15     #ffffff
font_family CommitMonoNerdFont
font_size 9.0
repaint_delay 50
enable_audio_bell no
window_margin_width 0
window_padding_width 0
single_window_padding_width -1
hide_window_decorations yes
confirm_os_window_close 0
