term xterm-kitty
font_family CommitMono Nerd Font
font_size 10

window_padding_width 4
placement_strategy center
confirm_os_window_close 0
enable_audio_bell no
visual_bell_duration 0
scrollback_lines 10000
copy_on_select clipboard
mouse_hide_wait 1.0

url_color #8bd5ca
url_style curly
open_url_with default
detect_urls yes

background #19191e
foreground #e3e3ea
cursor #c6a0f6
selection_foreground #19191e
selection_background #c6a0f6

color0 #23232a
color1 #ed8796
color2 #a6da95
color3 #eed49f
color4 #8aadf4
color5 #c6a0f6
color6 #8bd5ca
color7 #e3e3ea
color8 #a0a0b0
color9 #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #c6a0f6
color14 #8bd5ca
color15 #ffffff
