[colors]
foreground = "#e3e3ea"
background = "#19191e"
cursor = "#c6a0f6"
black = "#23232a"
bright_black = "#a0a0b0"
red = "#ed8796"
green = "#a6da95"
yellow = "#eed49f"
blue = "#8aadf4"
magenta = "#c6a0f6"
cyan = "#8bd5ca"
white = "#e3e3ea"
bright_white = "#ffffff"
