[colors]
foreground = "#e6e1cf"
background = "#0f1419"
cursor = "#ffb454"
black = "#161b22"
bright_black = "#5c6773"
red = "#ff7733"
green = "#b8cc52"
yellow = "#ffb454"
blue = "#59c2ff"
magenta = "#f07178"
cyan = "#39adb5"
white = "#e6e1cf"
bright_white = "#ffffff"
