[language-server.ts]
command = "typescript-language-server"
args = ["--stdio"]
language-id = "javascript"

[[language]]
name = "typescript"
auto-format = true
language-servers = ["ts"]

[[language]]
name = "javascript"
language-servers = ["ts"]
auto-format = true

[[language]]
name = "tsx"
language-servers = ["ts"]
auto-format = true

[[language]]
name = "jsx"
language-servers = ["ts"]
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright"]
auto-format = true
formatter = { command = "black", args = ["-"] }

[language-server.pyright.config]
venvPath = "."
venv = ".venv"
