set -gx XDG_CACHE_HOME "$HOME/code/.cache"
set -gx XDG_CONFIG_HOME "$HOME/.config"
set -gx XDG_DATA_HOME "$HOME/code/.local/share"
set -gx XDG_STATE_HOME "$HOME/code/.local/state"
set -gx GOCACHE "$XDG_CACHE_HOME/go-build"
set -gx GOMODCACHE "$XDG_CACHE_HOME/go-mod"
set -gx BUN_INSTALL_CACHE_DIR "$XDG_CACHE_HOME/bun/install/cache"

mkdir -p "$XDG_CACHE_HOME"
and mkdir -p "$XDG_CONFIG_HOME"
and mkdir -p "$XDG_DATA_HOME"
and mkdir -p "$XDG_STATE_HOME"
