sub-font="CommitMono Nerd Font"
sub-font-size=40
sub-color="%%foreground%%"
sub-border-color="%%background%%"
sub-border-size=3

vo=gpu
gpu-context=wayland

osd-color="%%color2%%"
osd-border-color="%%background%%"
