general {
    hide_cursor = true
    ignore_empty_input = true
    immediate_render = true
}

auth {
    pam:enabled = true
}

animations {
    enabled = false
}

background {
    monitor =
    path = ~/Pictures/backgrounds/megumin-vaporwave.jpg
    color = rgb(19191e)
    blur_passes = 0
}

input-field {
    monitor =
    size = 320, 56
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    rounding = 8
    outer_color = rgb(685878)
    inner_color = rgb(23232a)
    font_color = rgb(e3e3ea)
    fade_on_empty = false
    placeholder_text = <i>password</i>
    fail_text = <i>failed</i>
    check_color = rgb(c6a0f6)
    fail_color = rgb(ed8796)
    position = 0, -120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(e3e3ea)
    font_family = CommitMono Nerd Font
    font_size = 48
    position = 0, 70
    halign = center
    valign = center
}
