audio-resample-filter-size=32
audio-resample-linear=yes
audio-pitch-correction=yes
replaygain=track
audio-samplerate=0 
audio-format=float
vo=gpu
gpu-api=vulkan
hwdec=vaapi
video-sync=display-resample
interpolation=yes
tscale=oversample
gapless-audio=yes
volume-max=100
