vo=gpu-next
gpu-context=wayland
gpu-api=vulkan

deband=yes
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
linear-downscaling=yes
correct-downscaling=yes
interpolation=yes
tscale=oversample
video-sync=display-resample

target-peak=auto
audio-file-auto=fuzzy
sub-auto=fuzzy
sub-font="CommitMono Nerd Font"
sub-font-size=40
sub-color="#deffff"
sub-border-color="#050d17"
sub-border-size=3
osd-color="#205570"
osd-border-color="#050d17"
