stow_dir = "~/.dotfiles"

[[package]]
name = "bash"
target = "~"

[[package]]
name = "git"
target = "~"

[[package]]
name = "tmux"
target = "~"

[[package]]
name = "foot"
target = "~/.config/foot"

[[package]]
name = "mpv"
target = "~/.config/mpv"

[[package]]
name = "starship"
target = "~/.config/starship"

[[package]]
name = "fish"
target = "~/.config/fish"

[[package]]
name = "fnott"
target = "~/.config/fnott"

[[package]]
name = "sway"
target = "~/.config/sway"

[[package]]
name = "fastfetch"
target = "~/.config/fastfetch"

[[package]]
name = "waybar"
target = "~/.config/waybar"

[[package]]
name = "fuzzel"
target = "~/.config/fuzzel"

[[package]]
name = "stowme"
target = "~/.config/stowme"
