stow_dir = "~/.dotfiles"

[[package]]
name = "bash"
target = "~"

[[package]]
name = "git"
target = "~"

[[package]]
name = "ghostty"
target = "~/.config/ghostty"

[[package]]
name = "mpv"
target = "~/.config/mpv"

[[package]]
name = "starship"
target = "~/.config/starship"

[[package]]
name = "fish"
target = "~/.config/fish"
