stow_dir = "~/.dotfiles"

[[package]]
name = "X"
target = "~"

[[package]]
name = "bash"
target = "~"

[[package]]
name = "git"
target = "~"

[[package]]
name = "autostart"
target = "~/.config/autostart"

[[package]]
name = "helix"
target = "~/.config/helix"

[[package]]
name = "ghostty"
target = "~/.config/ghostty"

[[package]]
name = "i3"
target = "~/.config/i3"

[[package]]
name = "i3status-rust"
target = "~/.config/i3status-rust"

[[package]]
name = "mpv"
target = "~/.config/mpv"

[[package]]
name = "rofi"
target = "~/.config/rofi"

[[package]]
name = "starship"
target = "~/.config/starship"

[[package]]
name = "fish"
target = "~/.config/fish"

