[SupersonicTheme]
Name = "RoxySonic"
Version = "0.2"
SupportsDark = true
SupportsLight = false

[DarkColors]
PageBackground = "#%%color0.hex%%"
Background = "#%%color0.hex%%"
Foreground = "#ffffff"

ListHeader = "#%%color0.hex%%"
PageHeader = "#%%color0.hex%%"

InputBackground = "#%%color0.hex%%"
InputBorder = "#%%color8.hex%%"
MenuBackground = "#%%color0.hex%%"
OverlayBackground = "#%%color0.hex%%"

Button = "#%%color0.hex%%"
DisabledButton = "#%%color0.hex%%"

Pressed = "#%%color8.hex%%"
Hover = "#%%color8.hex%%"
ScrollBar = "#%%color8.hex%%"
Separator = "#%%color8.hex%%"

Primary = "#%%color4.hex%%"
Hyperlink = "#%%color6.hex%%"
Focus = "#%%color4.hex%%"

Error = "#%%color1.hex%%"
Warning = "#%%color3.hex%%"
Success = "#%%color2.hex%%"

Placeholder = "#%%color8.hex%%99"
Disabled = "#%%color8.hex%%77"
Shadow = "#00000088"
