# Generated by hellwal

export wallpaper='%%wallpaper%%'

export background='%%background%%'
export foreground='%%foreground%%'
export cursor='%%cursor%%'
export border='%%border%%'

export color0='%%color0.hex%%'
export color1='%%color1.hex%%'
export color2='%%color2.hex%%'
export color3='%%color3.hex%%'
export color4='%%color4.hex%%'
export color5='%%color5.hex%%'
export color6='%%color6.hex%%'
export color7='%%color7.hex%%'
export color8='%%color8.hex%%'
export color9='%%color9.hex%%'
export color10='%%color10.hex%%'
export color11='%%color11.hex%%'
export color12='%%color12.hex%%'
export color13='%%color13.hex%%'
export color14='%%color14.hex%%'
export color15='%%color15.hex%%'

export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

export LS_COLORS="$LS_COLORS:su=30;41:ow=30;42:st=30;44:"
